### ISSUE TITLE
Instructions how to use

### ISSUE THREAD

**Issue by nomidaepapi** [VaAndCob/ESP32-OBD2-Gauge#1]
Hello. Im tryping to make a OBD2 project with my Lexus GS300 2001 with a ESP32 and ELM327 bluetooth adapter 2.1. I want to use your lib to connect to the ELM327 and retrieve RPM values; but which code do i use exactly to do this?

**Comment by VaAndCob** [comment]
In the sketch. There are 4-5 sketches that run together for this project.
In case you want to read rpm or etc..
It's all about interpretation with elm327. 
I suggest you read more info about elm327 at command.
Or you can simply try elm327 bluetooth with Bluetooth terminal app and see how it responds.
If possible, i suggest you test your elm327 2.1 via obd2 app on store and see if your adapter is really compatible or works with your lexus car
