### ISSUE TITLE
i dont have the yellow display..but i have the 2.4inch spi interface display..

### ISSUE THREAD

**Issue by rohanjoshy2005** [VaAndCob/ESP32-OBD2-Gauge#3]
i dont have the yellow display..but i have the 2.4inch spi interface display...is this display compaitable with this project and can you give me the wiring digram

**Comment by VaAndCob** [comment]
This module tft screen use SPI as well. For the schematic diagram, it's in hardware folder.

**Comment by VaAndCob** [comment]
This module tft screen use SPI as well. For the schematic diagram, it's in hardware folder.

**Comment by rohanjoshy2005** [comment]
and i have the basic version of obd2..ELM327 mini...is it possible to do with it

**Comment by VaAndCob** [comment]
> and i have the basic version of obd2..ELM327 mini...is it possible to do with it

you can try, nobody can say, but I recommend original ELM327 with pic chip.

**Comment by rohanjoshy2005** [comment]
can you please give me the pinout for each components(not like diagram)like
vcc-3v,gnd-gnd like that

**Comment by VaAndCob** [comment]
> can you please give me the pinout for each components(not like diagram)like vcc-3v,gnd-gnd like that
> […](#)

you can google ESP32 and TFT 2.4" SPI example , connection, diagram and example code.
