### ISSUE TITLE
Question: Enclosure design files

### ISSUE THREAD

**Issue by aguedob** [VaAndCob/ESP32-OBD2-Gauge#4]
First of all, congrats for such a great project! I have one question for you. I really like the enclosure shown in your photos. Is 3d printed? Do you have the design files? Thank you!

**Comment by mateusleom** [comment]
[Case Esp32.zip](https://github.com/user-attachments/files/17074926/Case.Esp32.zip)
I made this myself, its similar to the one shown in the developer pictures

**Comment by VaAndCob** [comment]
> [Case Esp32.zip](https://github.com/user-attachments/files/17074926/Case.Esp32.zip) I made this myself, its similar to the one shown in the developer pictures

thank you mateusteom. very appreciated

**Comment by VaAndCob** [comment]
> First of all, congrats for such a great project! I have one question for you. I really like the enclosure shown in your photos. Is 3d printed? Do you have the design files? Thank you!

I upload 3d print file for this enclosure, you can see it in 'enclosure folder'
