### ISSUE TITLE
error: 'sigmaDeltaSetup' was not declared in this scope

### ISSUE THREAD

**Issue by amirzohaib** [VaAndCob/ESP32-OBD2-Gauge#6]
error: 'sigmaDeltaSetup' was not declared in this scope

in the nes_audio.cpp. maybe its a library i need to install?

**Comment by amirzohaib** [comment]
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\nes_audio.cpp: In member function 'void Cartridge::init()':
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\nes_audio.cpp:17:3: error: 'sigmaDeltaSetup' was not declared in this scope; did you mean 'sigmaDeltaDetach'?
   17 |   sigmaDeltaSetup(p1_pin, p1_channel, 88200);
      |   ^~~~~~~~~~~~~~~
      |   sigmaDeltaDetach
In file included from C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\ESP32-OBD2-Gauge-main.ino:258:
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h: In function 'void TaskPlayMusic(void*)':
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h:58:21: error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]
   58 |   esp_task_wdt_init(62, false);//62 sec wd timer / disable wd
      |                     ^~
      |                     |
      |                     int
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h:58:20: error: too many arguments to function 'esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t*)'
   58 |   esp_task_wdt_init(62, false);//62 sec wd timer / disable wd
      |   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h:5:
C:\Users\c9002481\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-bd2b9390ef\esp32/include/esp_system/include/esp_task_wdt.h:47:11: note: declared here
   47 | esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t *config);
      |           ^~~~~~~~~~~~~~~~~
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h: In function 'void configMenu()':
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h:715:13: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
  715 |             ledcAttachPin(BUZZER_PIN, buzzerChannel);//reattach buzzer pin
      |             ^~~~~~~~~~~~~
      |             ledcAttach
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\ESP32-OBD2-Gauge-main.ino: In function 'void setup()':
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\ESP32-OBD2-Gauge-main.ino:274:3: error: 'ledcSetup' was not declared in this scope
  274 |   ledcSetup(buzzerChannel, 1500, 10);//buzzer 10 bit
      |   ^~~~~~~~~
C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\ESP32-OBD2-Gauge-main.ino:276:3: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
  276 |   ledcAttachPin(BUZZER_PIN, buzzerChannel);//attach buzzer
      |   ^~~~~~~~~~~~~
      |   ledcAttach
Multiple libraries were found for "SD.h"
  Used: C:\Users\c9002481\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.2\libraries\SD
  Not used: C:\Users\c9002481\AppData\Local\Arduino15\libraries\SD
exit status 1

Compilation error: 'sigmaDeltaSetup' was not declared in this scope; did you mean 'sigmaDeltaDetach'?

**Comment by VaAndCob** [comment]
please check if you use  ESP32 Arduino core 2.0.7,  it's not compatible with new COre 3.xx

**Comment by VaAndCob** [comment]
> C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\nes_audio.cpp: In member function 'void Cartridge::init()': C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\nes_audio.cpp:17:3: error: 'sigmaDeltaSetup' was not declared in this scope; did you mean 'sigmaDeltaDetach'? 17 | sigmaDeltaSetup(p1_pin, p1_channel, 88200); | ^~~~~~~~~~~~~~~ | sigmaDeltaDetach In file included from C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\ESP32-OBD2-Gauge-main.ino:258: C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h: In function 'void TaskPlayMusic(void*)': C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h:58:21: error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive] 58 | esp_task_wdt_init(62, false);//62 sec wd timer / disable wd | ^~ | | | int C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h:58:20: error: too many arguments to function 'esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t*)' 58 | esp_task_wdt_init(62, false);//62 sec wd timer / disable wd | ~~~~~~~~~~~~~~~~~^~~~~~~~~~~ In file included from C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h:5: C:\Users\c9002481\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-bd2b9390ef\esp32/include/esp_system/include/esp_task_wdt.h:47:11: note: declared here 47 | esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t *config); | ^~~~~~~~~~~~~~~~~ C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h: In function 'void configMenu()': C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\config.h:715:13: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'? 715 | ledcAttachPin(BUZZER_PIN, buzzerChannel);//reattach buzzer pin | ^~~~~~~~~~~~~ | ledcAttach C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\ESP32-OBD2-Gauge-main.ino: In function 'void setup()': C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\ESP32-OBD2-Gauge-main.ino:274:3: error: 'ledcSetup' was not declared in this scope 274 | ledcSetup(buzzerChannel, 1500, 10);//buzzer 10 bit | ^~~~~~~~~ C:\Users\c9002481\Documents\Platform IO\ESP32-OBD2-Gauge-main\ESP32-OBD2-Gauge-main.ino:276:3: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'? 276 | ledcAttachPin(BUZZER_PIN, buzzerChannel);//attach buzzer | ^~~~~~~~~~~~~ | ledcAttach Multiple libraries were found for "SD.h" Used: C:\Users\c9002481\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.2\libraries\SD Not used: C:\Users\c9002481\AppData\Local\Arduino15\libraries\SD exit status 1
> 
> Compilation error: 'sigmaDeltaSetup' was not declared in this scope; did you mean 'sigmaDeltaDetach'?

please check if your arduino  esp32 cord is version 2.0.17,  not 3.0.x  
a new core update incompatible with some libraries.

**Comment by GerryGit** [comment]
Core 2.0.17 no longer exists. It was replaced with Core 2.0.18. When buidlng with core 2.0.18 this bug still exists.

**Comment by VaAndCob** [comment]
> Core 2.0.17 no longer exists. It was replaced with Core 2.0.18. When buidlng with core 2.0.18 this bug still exists. 

Actually you can select to install 2.0.17.  Whatis the bug or error report?

**Comment by GerryGit** [comment]
Thanks, I did find and install 2.0.17 and could build with no errors.
